<?php
/*
 * Mageho
 * Ilan PARMENTIER
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0) that is available
 * through the world-wide-web at this URL: http://www.opensource.org/licenses/OSL-3.0
 * If you are unable to obtain it through the world-wide-web, please send an email
 * to contact@mageho.com so we can send you a copy immediately.
 *
 * @category     Mageho
 * @package     Mageho_Atos
 * @author       Mageho, Ilan PARMENTIER <contact@mageho.com>
 * @copyright   Copyright (c) 2015 Mageho (http://www.mageho.com)
 * @license      http://www.opensource.org/licenses/OSL-3.0  Open Software License (OSL 3.0)
 */
 
 	$_code = $this->getMethodCode();
 	$_term = $this->getTerm();
 	$_nb = $this->getNb();
 	$_total = $this->getTotal();
?>
<br />
<b class="text-lg"><?php echo $this->__('Pay'); ?> <?php echo $_nb; ?> * <?php echo $this->helper('core')->currency($_term); ?></b><br />
<small><?php echo $this->__('For information, your total order is %s', $this->helper('core')->currency($_total, true, false)); ?></small>