<?php
/*
 * Mageho
 * Ilan PARMENTIER
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0) that is available
 * through the world-wide-web at this URL: http://www.opensource.org/licenses/OSL-3.0
 * If you are unable to obtain it through the world-wide-web, please send an email
 * to contact@mageho.com so we can send you a copy immediately.
 *
 * @category     Mageho
 * @package     Mageho_Atos
 * @author       Mageho, Ilan PARMENTIER <contact@mageho.com>
 * @copyright   Copyright (c) 2014  Mageho (http://www.mageho.com)
 * @license      http://www.opensource.org/licenses/OSL-3.0  Open Software License (OSL 3.0)
 */
 
 	$_code = $this->getMethodCode();
 	$_paymentMeans = $this->getPaymentMeans(); 
?>
<?php if ($_paymentMeans): ?>
<fieldset id="payment_form_<?php echo $_code; ?>" class="form-list" style="display:none">
    <div class="atos-select-cards well">
    	<p class="choc"><?php echo $this->__('Select a credit card'); ?></p>
        <ol>
            <?php foreach($_paymentMeans as $key => $value): ?>
            <li>
            	<label for="<?php echo $value['id']; ?>">
					<input type="radio" name="payment[atos_standard_payment_means]" value="<?php echo $key; ?>" id="<?php echo $value['id']; ?>" class="atos_cc validate-one-required-by-name" <?php if ($this->getSelectedMethod() == $key): ?>checked="checked"<?php endif; ?> />
					<img src="<?php echo $value['src']; ?>" alt="<?php echo $value['alt']; ?>" />
				</label>
            </li>
            <?php endforeach; ?>
        </ol>        
        <div class="clearfix"></div>
        <div id="atos_aurore_dob">
	        <hr role="presentation" />
	        
	        <p><?php echo $this->__('To pay with Aurore, we need your birth date. Please, check it.'); ?></p>
		    <?php echo 
			    $this->getLayout()
			    	->createBlock('customer/widget_dob')
			    	->setDate($this->getCustomerDob())
			    	->setFieldIdFormat('payment:aurore_%s')
			    	->setFieldNameFormat('payment[aurore_%s]')
			    	->toHtml() 
			?>
        </div>
	    
	    <script>
		/* <![CDATA[ */
	        var atosAuroreMethod = $('<?php echo $_code ?>_atos_cc_aurore');
	        if (atosAuroreMethod.checked === false) {
	        	$('atos_aurore_dob').hide();
	        }
	        
	        $$('.atos_cc').each(function(element) {
		        element.observe('change', function() {
			        if (this.id == atosAuroreMethod.id) {
			    		$('atos_aurore_dob').toggle();
				    } else {
					    $('atos_aurore_dob').hide();
					}
		        });
		    });
		/* ]]> */
	   </script>
    </div>
    <div class="atos-cms-block"><?php echo $this->getCmsBlock(); ?></div>
</fieldset>
<?php endif; ?>