<?php
/*
 * Mageho
 * Ilan PARMENTIER
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0) that is available
 * through the world-wide-web at this URL: http://www.opensource.org/licenses/OSL-3.0
 * If you are unable to obtain it through the world-wide-web, please send an email
 * to contact@mageho.com so we can send you a copy immediately.
 *
 * @category     Mageho
 * @package     Mageho_Atos
 * @author       Mageho, Ilan PARMENTIER <contact@mageho.com>
 * @copyright   Copyright (c) 2015 Mageho (http://www.mageho.com)
 * @license      http://www.opensource.org/licenses/OSL-3.0  Open Software License (OSL 3.0)
 */
 
	 $title = $this->__('An error occurred in the process of payment');
	 if ($this->getTitle()) {
		 $title = $this->getTitle();
	 }
?>
<div id="atos-failure-wrapper">
	<div class="page-title">
	    <h1><?php echo $title; ?></h1>
	</div>
	
	<ul class="note-msg">
		<li><?php echo $this->__('Choose an another payment method or contact us by phone at %s to validate your order.', Mage::getStoreConfig('general/store_information/phone')); ?></li>
	</ul>
	
	<?php if ($this->getMessage()): ?>
	<p><?php echo $this->getMessage(); ?></p>
	<?php endif; ?>
	
	<?php echo $this->getChildHtml('atos.failure.extra.blocks'); ?>
	
	<div class="buttons-set">
		<p class="f-left left"><?php echo $this->__('Click <a href="%s">here</a> to continue shopping.', $this->helper('checkout/url')->getCartUrl()) ?></p>
		
		<?php if ($this->getButtonUrl() && $this->getButtonText()): ?>
		<p class="f-right right">
			<a href="<?php echo $this->escapeUrl($this->getButtonUrl()); ?>" role="button" class="btn btn-danger btn-lg">
				<?php echo $this->escapeHtml($this->getButtonText()); ?>
			</a>
		</p>
		<?php endif; ?>
	</div>
</div>