<?php
/*
 * Mageho
 * Ilan PARMENTIER
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0) that is available
 * through the world-wide-web at this URL: http://www.opensource.org/licenses/OSL-3.0
 * If you are unable to obtain it through the world-wide-web, please send an email
 * to contact@mageho.com so we can send you a copy immediately.
 *
 * @category     Mageho
 * @package     Mageho_Atos
 * @author       Mageho, Ilan PARMENTIER <contact@mageho.com>
 * @copyright   Copyright (c) 2015 Mageho (http://www.mageho.com)
 * @license      http://www.opensource.org/licenses/OSL-3.0  Open Software License (OSL 3.0)
 */
 
 	$hash = unserialize($this->getInfo()->getAdditionalData());
 	$apiResponse = Mage::getSingleton('atos/api_response');
 	$paymentN = $apiResponse->paymentN($hash);
 	$hlpr = $this->helper('atos');
?>

<div id="atos-logo">&nbsp;</div>

<p><strong><?php echo $this->escapeHtml($this->getMethod()->getTitle()); ?></strong></p>

<?php if ($this->isOrderPlacedFromFrontend()): ?>
<ul class="messages">
	<?php if (isset($hash['response_code'])): ?>
	
		<?php if ($hash['response_code'] == '00'): ?>
	    <li class="success-msg"><?php echo $hlpr->__('Payment accepted by Atos'); ?></li>
	    <?php else: ?>
	    <li class="warning-msg"><?php echo $hlpr->__('Customer was rejected by Atos'); ?></li>
	    <?php endif; ?>
	    
    <?php else: ?>
    <li class="warning-msg"><?php echo $hlpr->__('The customer left without paying'); ?></li>
    <?php endif; ?>
</ul>

<?php
/*
 *
 * Details de la transaction
 *
 *
 */
?>
<?php if (isset($hash['transaction_id'], $hash['response_code'])): ?>
<div class="grid">
	<table class="atowpseveral">
		<thead>
	    	<tr class="headings">
	        	<th><?php echo $hlpr->__('Credit Card'); ?></th>
	            <th><?php echo $hlpr->__('Payment Informations'); ?></th>
	            <th><?php echo $hlpr->__('Payment Due Dates'); ?></th>
	        </tr>
	    </thead>
		<tbody>
	    	<tr>
	        	<td class="payment-means first"><img src="<?php echo $this->getCreditCardImgSrc(strtolower($hash['payment_means'])); ?>" alt="<?php echo $hash['payment_means']; ?>" title="<?php echo $hash['payment_means']; ?>" /></td>
	            <td class="payment-infos">
	                <ul>
	                    <li><?php echo $hlpr->__('Number of monthly'); ?> <?php echo $paymentN['payment_n']; ?></li>
	                    <li><?php echo $hlpr->__('Debit every %d days', $paymentN['period']); ?></li>
	                    <li><?php echo $hlpr->__('First debit'); ?> <?php echo $apiResponse->formatAmount($paymentN['initial_amount']); ?></li>
	                </ul>
	            </td>
	            <td class="payment-due-dates last">
	            	<ol>
						<?php foreach ($paymentN['payment_due_dates'] as $date): ?>
	                    <li><?php echo $date; ?></li>
	                    <?php endforeach; ?>
	                </ol>
	            </td>
	        </tr>	
	    </tbody>
	</table>
</div>

<div class="more"><a href="#response" onclick="Effect.toggle('response', 'blind'); return false;" onkeypress="Effect.toggle('response', 'blind'); return false;"><?php echo $hlpr->__('More Informations'); ?></a></div>
<div id="response" style="display:none">
	<div class="grid">
		<table class="border">
			<tbody>
				<tr>
					<th><?php echo $hlpr->__('Transaction Number'); ?></th>
					<td><?php echo $hash['transaction_id']; ?></td>
				</tr>
				
				<?php if (isset($hash['capture_mode']) && !empty($hash['capture_mode'])): ?>
				<tr class="even">
					<th><?php echo $hlpr->__('Capture Mode'); ?></th>
					<td><?php echo $hash['capture_mode']; ?></td>
				</tr>
				<?php endif; ?>
				
				<tr>
					<th><?php echo $hlpr->__('Day before the capture'); ?></th>
					<td>
						<?php if (isset($hash['capture_day'])  && $hash['capture_day'] > 0): ?>
						<?php echo $hash['capture_day']; ?>
						<?php else: ?>
						<?php echo $hlpr->__('Day before capture: immediate capture'); ?>
						<?php endif; ?>
					</td>
				</tr>
						
				<?php if ($cc = $apiResponse->getCcNumberEnc($hash['card_number'])): ?>
				<tr class="even">
					<th><?php echo $hlpr->__('Credit card number'); ?></th>
					<td><?php echo $cc; ?></td>
				</tr>
				<?php endif; ?>
					
				<?php if (isset($hash['cvv_response_code']) && $cvvResponseLabel = $apiResponse->getCvvResponseLabel($hash)): ?>
				<tr>
					<th><?php echo $hlpr->__('About CVV credit card'); ?></th>
					<td><?php echo $cvvResponseLabel; ?></td>
				</tr>
				<?php endif; ?>
							
				<?php if (isset($hash['response_code']) && $responseLabel = $apiResponse->getResponseLabel($hash)): ?>
				<tr class="even">
					<th><?php echo $hlpr->__('Response code'); ?></th>
					<td><?php echo $responseLabel; ?></td>
				</tr>
				<?php endif; ?>
							
				<?php if (isset($hash['bank_response_code']) && $bankResponseLabel = $apiResponse->getBankResponseLabel($hash)): ?>
				<tr>
					<th><?php echo $hlpr->__('Response code of the bank'); ?></th>
					<td><?php echo $bankResponseLabel; ?></td>
				</tr>
				<?php endif; ?>
							
				<?php if (isset($hash['complementary_code']) && $complementaryCode = $apiResponse->getComplementaryCode($hash)): ?>
				<tr class="even">
					<th><?php echo $hlpr->__('Additional control'); ?></th>
					<td><?php echo $complementaryCode; ?></td>
				</tr>
				<?php endif; ?>
							
				<?php if (isset($hash['transaction_condition']) && $transactionConditionLabel = $apiResponse->getTransactionConditionLabel($hash)): ?>
				<tr>
					<th><?php echo $hlpr->__('Transaction condition'); ?></th>
					<td><?php echo $transactionConditionLabel; ?></td>
				</tr>
				<?php endif; ?>
			</tbody>
		</table>
	</div>
</div>
<?php endif; ?>
<?php endif; ?>

<div class="divider">&nbsp;</div>